apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nest-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nest-service
    spec:
      containers:
        - image: "2nnar/nest-service"
          imagePullPolicy: Always
          name: nest-service
          ports:
            - containerPort: 80
