apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: nest-service.api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nest-service
                port:
                  number: 5005