apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-service
spec:
  rules:
  - host: nest-service.api
    http:
      paths:
      - path: /
        backend:
          serviceName: nest-service
          servicePort: 80